
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: Custom_chat_development
  username: Custom_chat_admin
  password: admin
  host: localhost

test:
  <<: *development
  database: Custom_chat

